# DevRev Search Dataset

Loading and exploring the `devrev/search` dataset from Hugging Face.

**Dataset Structure:**
- `annotated_queries` — Queries paired with annotated (golden) article chunks
- `knowledge_base` — Article chunks from DevRev's customer-facing support documentation
- `test_queries` — Held-out queries used for evaluation

In [1]:
from datasets import load_dataset
import pandas as pd

/Users/prakharagarwal/devrev/devrev-search-bench/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Load Annotated Queries
Queries paired with annotated (golden) article chunks for training/validation.

In [2]:
# Load annotated queries
annotated_queries = load_dataset("devrev/search", "annotated_queries")
print(annotated_queries)

Generating train split: 100%|██████████| 291/291 [00:00<00:00, 36370.05 examples/s]

DatasetDict({
    train: Dataset({
        features: ['query_id', 'query', 'retrievals'],
        num_rows: 291
    })
})

In [3]:
# Convert to DataFrame and display
annotated_df = annotated_queries["train"].to_pandas()
annotated_df.head()

,query_id,query,retrievals
0,0ae94217-c6a0-4895-83a2-841a95f01637,create DevRev ticket from Microsoft Teams,"[{'id': 'ART-4216_KNOWLEDGE_NODE-26', 'text': ..."
1,d0b209b3-6cea-46d8-bfac-bd0e286ea21b,workflow builder auto close ticket after 48 ho...,"[{'id': 'ART-2012_KNOWLEDGE_NODE-24', 'text': ..."
2,40c1aa6f-cd21-46ab-8f6f-76fdc267b584,automated reminder to customer ticket will be ...,"[{'id': 'ART-3068_KNOWLEDGE_NODE-24', 'text': ..."
3,e47d883f-b712-4f98-bd06-14ade143e3c2,connect Bitbucket account to DevRev account,"[{'id': 'ART-2030_KNOWLEDGE_NODE-27', 'text': ..."
4,2e6f9413-15ac-4974-a380-7aa22fc98a61,use of workflows in DevRev,"[{'id': 'ART-1961_KNOWLEDGE_NODE-28', 'text': ..."

In [4]:
# Sample a single annotated query example
annotated_queries["train"][0]

{'query_id': '0ae94217-c6a0-4895-83a2-841a95f01637',
 'query': 'create DevRev ticket from Microsoft Teams',
 'retrievals': [{'id': 'ART-4216_KNOWLEDGE_NODE-26',
   'text': 'DevRev Object | Sync to DevRev |\\n| --- | --- | --- |\\n| Plan | Parts | \\xe2\\x9c\\x85 |\\n| User | Identity/DevUser | \\xe2\\x9c\\x85 |\\n| Channel | Chat | \\xe2\\x9c\\x85 |\\n| Attachments in Message/Thread/Task | Artifacts on Article | \\xe2\\x9c\\x85 |\\n| Message | Comment | \\xe2\\x9c\\x85 |\\n| Thread | Comment | \\xe2\\x9c\\x85 |\\n| Task | Issue/Ticket | \\xe2\\x9c\\x85 |\\n\\nImporting from Microsoft Teams\\n------------------------------\\n\\nFollow the steps below to import from Microsoft Teams:\\n\\n1. Go to',
   'title': 'Microsoft Teams AirSync | AirSync | Snap-ins | DevRev'},
  {'id': 'ART-4216_KNOWLEDGE_NODE-29',
   'text': 'with many\\nattachments. DevRev honors the Microsoft Graph API rate limits and back-off and resumes automatically.\\n\\nPost import options\\n-------------------\\n\\nAfter a successful import, you have the following options available for the imported account:\\n\\n* **Sync to DevRev**  \\n  This option allows you to synchronize any modifications made in Microsoft Teams with the corresponding items previously imported into DevRev. It also creates new items in DevRev for any new data in Microsoft Teams',
   'title': 'Microsoft Teams AirSync | AirSync | Snap-ins | DevRev'}]}

## 2. Load Test Queries
Held-out queries used for evaluation.

In [5]:
# Load test queries
test_queries = load_dataset("devrev/search", "test_queries")
print(test_queries)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Generating test split: 100%|██████████| 92/92 [00:00<00:00, 35466.54 examples/s]

DatasetDict({
    test: Dataset({
        features: ['query_id', 'query'],
        num_rows: 92
    })
})

In [6]:
# Convert to DataFrame and display
test_df = test_queries["test"].to_pandas()
test_df.head()

,query_id,query
0,a97f93d2-410a-431f-ae9a-1e23ed35d74c,end customer organization name not appearing i...
1,7dd7e2b4-9349-4535-8007-1d706e0fabff,Android SDK session generated with Unknown user
2,4bc92187-cdaa-4c20-b189-abd1672e5a71,email reply received on wrong ticket
3,4d9878e8-f746-4df5-8bf6-f9444989b385,manage access and privileges in DevRev
4,483151ec-aff4-4569-b3df-651f578b61d8,SSO setup SAML IDP metadata connection string ...

In [7]:
# Sample a single test query example
test_queries["test"][0]

{'query_id': 'a97f93d2-410a-431f-ae9a-1e23ed35d74c',
 'query': 'end customer organization name not appearing in ticket or conversation'}

## 3. Load Knowledge Base
Article chunks from DevRev's customer-facing support documentation.

In [8]:
# Load knowledge base
knowledge_base = load_dataset("devrev/search", "knowledge_base")
print(knowledge_base)

Generating corpus split: 100%|██████████| 65224/65224 [00:00<00:00, 1493567.46 examples/s]

DatasetDict({
    corpus: Dataset({
        features: ['id', 'text', 'title'],
        num_rows: 65224
    })
})

In [9]:
# Convert to DataFrame and display
knowledge_df = knowledge_base["corpus"].to_pandas()
knowledge_df.head()

,id,text,title
0,ART-17711_KNOWLEDGE_NODE-0,b'We ran into a case where an AirSync was star...,Sync fails when original sync owners loses per...
1,ART-17711_KNOWLEDGE_NODE-1,access.\n\nOnce Person A was re-added with the...,Sync fails when original sync owners loses per...
2,ART-17650_KNOWLEDGE_NODE-0,"b""American cybersecurity leader unifies securi...",American cybersecurity leader unifies security...
3,ART-17650_KNOWLEDGE_NODE-1,DevRev\n======================================...,American cybersecurity leader unifies security...
4,ART-17650_KNOWLEDGE_NODE-2,solutions help organisations build and deploy ...,American cybersecurity leader unifies security...

In [10]:
# Sample a single knowledge base chunk
knowledge_base["corpus"][0]

{'id': 'ART-17711_KNOWLEDGE_NODE-0',
 'text': "b'We ran into a case where an AirSync was started by one person (Person A) and later failed. Another user (Person B) tried to click Retry, but it didn\\xe2\\x80\\x99t work. The logs showed 401 and 403 errors in communication between the snap-in and the snap-in manager.\\n\\nIt turned out that AirSync assigns the sync owner to whoever started it. Since Person A had been removed from the org or lost permissions, the retry failed \\xe2\\x80\\x94 the system still expected the original owner to have valid",
 'title': 'Sync fails when original sync owners loses permissions'}

## 4. Dataset Summary

In [11]:
print("=" * 60)
print("DevRev Search Dataset Summary")
print("=" * 60)
print(f"\nAnnotated Queries:")
print(annotated_queries)
print(f"\nTest Queries:")
print(test_queries)
print(f"\nKnowledge Base:")
print(knowledge_base)
print("\n" + "=" * 60)

============================================================
DevRev Search Dataset Summary
============================================================

Annotated Queries:
DatasetDict({
    train: Dataset({
        features: ['query_id', 'query', 'retrievals'],
        num_rows: 291
    })
})

Test Queries:
DatasetDict({
    test: Dataset({
        features: ['query_id', 'query'],
        num_rows: 92
    })
})

Knowledge Base:
DatasetDict({
    corpus: Dataset({
        features: ['id', 'text', 'title'],
        num_rows: 65224
    })
})

============================================================

---
## 5. Index Knowledge Base with FAISS

Use either OpenAI (`text-embedding-3-small`) or Ollama (`qwen3-embedding:0.6b`) embeddings with the same FAISS pipeline.

In [12]:
try:
    from openai import OpenAI
except ImportError:
    OpenAI = None

import faiss
import numpy as np
from tqdm import tqdm
import time
import os
import json
import pickle

In [14]:
# Embedding backend configuration
# Switch this to "ollama" to run the same FAISS pipeline locally.
EMBEDDING_PROVIDER = "ollama"  # "openai" | "ollama"

OPENAI_MODEL_ID = "text-embedding-3-small"
OLLAMA_MODEL_ID = "qwen3-embedding:0.6b"

client = None
if EMBEDDING_PROVIDER == "openai":
    if OpenAI is None:
        raise ImportError("openai package is not installed. Run: pip install openai")

    # Set your API key as an environment variable: export OPENAI_API_KEY="your-key-here"
    OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
    if not OPENAI_API_KEY:
        raise ValueError("Please set OPENAI_API_KEY when EMBEDDING_PROVIDER='openai'")

    client = OpenAI(api_key=OPENAI_API_KEY)
    MODEL_ID = OPENAI_MODEL_ID
elif EMBEDDING_PROVIDER == "ollama":
    import ollama
    MODEL_ID = OLLAMA_MODEL_ID
else:
    raise ValueError("EMBEDDING_PROVIDER must be either 'openai' or 'ollama'")

print(f"Using model: {MODEL_ID}")
print(f"Provider: {EMBEDDING_PROVIDER}")

Using model: qwen3-embedding:0.6b
Provider: ollama

In [15]:
def get_embedding_openai(text: str) -> np.ndarray:
    response = client.embeddings.create(
        model=MODEL_ID,
        input=text
    )
    return np.array(response.data[0].embedding, dtype=np.float32)


def get_embedding_ollama(text: str) -> np.ndarray:
    response = ollama.embed(
        model=MODEL_ID,
        input=text,
    )
    embeddings = response.embeddings if hasattr(response, "embeddings") else response["embeddings"]
    embedding = embeddings[0] if embeddings and isinstance(embeddings[0], list) else embeddings
    return np.array(embedding, dtype=np.float32)


def get_embedding(text: str) -> np.ndarray:
    """Get embedding for a single text using the configured provider."""
    if EMBEDDING_PROVIDER == "openai":
        return get_embedding_openai(text)
    return get_embedding_ollama(text)

In [16]:
def get_embeddings_batch(texts: list) -> np.ndarray:
    """Get embeddings for a batch of texts using the configured provider."""
    if EMBEDDING_PROVIDER == "openai":
        response = client.embeddings.create(
            model=MODEL_ID,
            input=texts
        )
        return np.array([d.embedding for d in response.data], dtype=np.float32)

    # Ollama Python client does not provide a stable batch API shape across versions,
    # so we embed one-by-one and stack.
    return np.vstack([get_embedding_ollama(text) for text in texts]).astype(np.float32)

In [17]:
# Test the configured embedding provider
test_embedding = get_embedding("This is a test sentence.")
print(f"Provider: {EMBEDDING_PROVIDER}")
print(f"Test embedding shape: {test_embedding.shape}")
print(f"Embedding dimension: {len(test_embedding)}")
print(f"First 5 values: {test_embedding[:5]}")

Provider: ollama
Test embedding shape: (1024,)
Embedding dimension: 1024
First 5 values: [-0.02046742 -0.02415173 -0.00554356 -0.05601534 -0.00608756]

In [19]:
# Prepare documents: concatenate title with text
corpus = knowledge_base["corpus"]

documents = []
doc_ids = []
doc_titles = []
doc_texts = []

for item in tqdm(corpus, desc="Preparing documents"):
    # Concatenate title and text
    doc_text = f"{item['title']}\n\n{item['text']}"
    documents.append(doc_text)
    doc_ids.append(item['id'])
    doc_titles.append(item['title'])
    doc_texts.append(item['text'])

print(f"\nTotal documents: {len(documents):,}")
print(f"\nSample document:")
print(documents[0][:500])

Preparing documents: 100%|██████████| 65224/65224 [00:00<00:00, 97638.25it/s]

Total documents: 65,224

Sample document:
Sync fails when original sync owners loses permissions

b'We ran into a case where an AirSync was started by one person (Person A) and later failed. Another user (Person B) tried to click Retry, but it didn\xe2\x80\x99t work. The logs showed 401 and 403 errors in communication between the snap-in and the snap-in manager.\n\nIt turned out that AirSync assigns the sync owner to whoever started it. Since Person A had been removed from the org or lost permissions, the retry failed \xe2\x80\x94 the s

In [20]:
def get_all_embeddings(texts, batch_size=100, max_retries=3):
    """Get embeddings for all texts using the configured provider."""
    all_embeddings = []
    embedding_dim = None

    for i in tqdm(range(0, len(texts), batch_size), desc="Generating embeddings"):
        batch = texts[i:i + batch_size]

        # Keep OpenAI requests under practical input limits.
        if EMBEDDING_PROVIDER == "openai":
            batch = [text[:8000] if len(text) > 8000 else text for text in batch]

        retries = 0
        while retries < max_retries:
            try:
                embeddings = get_embeddings_batch(batch)
                if embedding_dim is None:
                    embedding_dim = embeddings.shape[1]
                all_embeddings.append(embeddings)
                break
            except Exception as e:
                retries += 1
                if retries >= max_retries:
                    print(f"Error embedding batch {i}: {e}")
                    fallback_dim = embedding_dim if embedding_dim is not None else len(get_embedding("dimension probe"))
                    all_embeddings.append(np.zeros((len(batch), fallback_dim), dtype=np.float32))
                else:
                    print(f"Retry {retries} for batch {i}...")
                    time.sleep(2)

        time.sleep(0.1)  # light rate limiting

    return np.vstack(all_embeddings)

In [ ]:
# Generate embeddings for all documents
print("Generating embeddings for knowledge base...")
print(f"Total documents: {len(documents):,}")
print("Using batch processing for efficiency...")

# For testing, use a subset (uncomment for all documents)
# documents_to_embed = documents[:100]  # Test with first 100 docs
documents_to_embed = documents  # All documents

embeddings = get_all_embeddings(documents_to_embed, batch_size=10)
print(f"\nEmbeddings shape: {embeddings.shape}")

# Save embeddings
np.save("embeddings.npy", embeddings)
print("Embeddings saved to embeddings.npy")

In [ ]:
# Load embeddings if already saved
# embeddings = np.load("embeddings.npy")
# print(f"Loaded embeddings shape: {embeddings.shape}")

In [ ]:
# Create FAISS index
embedding_dim = embeddings.shape[1]
print(f"Creating FAISS index with dimension: {embedding_dim}")

# Normalize embeddings for cosine similarity
embeddings_normalized = embeddings.copy().astype('float32')
faiss.normalize_L2(embeddings_normalized)

# Create the index using IndexFlatIP for inner product (cosine similarity with normalized vectors)
index = faiss.IndexFlatIP(embedding_dim)
index.add(embeddings_normalized)

print(f"Index created with {index.ntotal:,} vectors")

In [ ]:
# Save the index and document mapping
INDEX_DIR = "faiss_index"
os.makedirs(INDEX_DIR, exist_ok=True)

# Save FAISS index
faiss.write_index(index, os.path.join(INDEX_DIR, "knowledge_base.index"))

# Save document mapping
with open(os.path.join(INDEX_DIR, "doc_mapping.pkl"), "wb") as f:
    pickle.dump({
        "doc_ids": doc_ids,
        "documents": documents,
        "doc_titles": doc_titles,
        "doc_texts": doc_texts
    }, f)

print(f"✓ Index saved to {INDEX_DIR}/knowledge_base.index")
print(f"✓ Document mapping saved to {INDEX_DIR}/doc_mapping.pkl")

## 6. Search the Knowledge Base

In [ ]:
def search(query: str, k: int = 5):
    """Search the knowledge base for relevant documents."""
    query_embedding = get_embedding(query).astype('float32')
    query_embedding = query_embedding.reshape(1, -1)
    faiss.normalize_L2(query_embedding)
    
    scores, indices = index.search(query_embedding, k)
    
    results = []
    for i, (score, idx) in enumerate(zip(scores[0], indices[0])):
        results.append({
            "rank": i + 1,
            "score": float(score),
            "id": doc_ids[idx],
            "title": doc_titles[idx],
            "text": doc_texts[idx]
        })
    
    return results

In [ ]:
# Test search with a sample query
query = "How do I set up AirSync?"
results = search(query, k=5)

print(f"Query: {query}")
print("=" * 60)

for r in results:
    print(f"\n[Rank {r['rank']}] Score: {r['score']:.4f}")
    print(f"Doc ID: {r['id']}")
    print(f"Title: {r['title']}")
    print(f"Text: {r['text'][:300]}...")
    print("-" * 40)

---
## 7. Run Evaluation on Test Queries

Run search against all test queries and save results in the same format as annotated_queries.

In [ ]:
# Run search on all test queries - DIRECT VERSION (no dependency on search function)
TOP_K = 10  # Number of retrievals per query

# Get corpus data for lookups
corpus_data = knowledge_base["corpus"]

test_results = []

for item in tqdm(test_queries["test"], desc="Processing test queries"):
    query_id = item["query_id"]
    query = item["query"]
    
    # Get query embedding directly
    query_embedding = get_embedding(query).astype('float32').reshape(1, -1)
    faiss.normalize_L2(query_embedding)
    
    # Search FAISS index
    scores, indices = index.search(query_embedding, TOP_K)
    
    # Format retrievals using corpus data directly
    retrievals = []
    for idx in indices[0]:
        doc = corpus_data[int(idx)]
        retrievals.append({
            "id": doc["id"],
            "text": doc["text"],
            "title": doc["title"]
        })
    
    test_results.append({
        "query_id": query_id,
        "query": query,
        "retrievals": retrievals
    })

print(f"\nProcessed {len(test_results)} test queries")

In [ ]:
# Preview a sample result
import json
print("Sample result:")
print(json.dumps(test_results[0], indent=2, default=str)[:1500])

In [ ]:
# Save results to JSON file
OUTPUT_FILE = "test_queries_results.json"

with open(OUTPUT_FILE, "w") as f:
    json.dump(test_results, f, indent=2)

print(f"✓ Results saved to {OUTPUT_FILE}")
print(f"  - {len(test_results)} queries")
print(f"  - {TOP_K} retrievals per query")

In [ ]:
# Also save as a parquet file for easier loading
results_df = pd.DataFrame(test_results)
results_df.to_parquet("test_queries_results.parquet", index=False)
print("✓ Results also saved to test_queries_results.parquet")

In [ ]:
# Display results summary
print("=" * 60)
print("Test Queries Results Summary")
print("=" * 60)
print(f"Total queries: {len(test_results)}")
print(f"Retrievals per query: {TOP_K}")
print(f"\nOutput files:")
print(f"  - test_queries_results.json")
print(f"  - test_queries_results.parquet")
print("\nFormat matches annotated_queries structure:")
print("  - query_id: string")
print("  - query: string")
print("  - retrievals: list of {id, text, title}")

## 8. Load Saved Index (Optional)
Use this to load a previously saved index without re-embedding.

In [ ]:
# Load saved index and mapping
# INDEX_DIR = "faiss_index"
# index = faiss.read_index(os.path.join(INDEX_DIR, "knowledge_base.index"))
# with open(os.path.join(INDEX_DIR, "doc_mapping.pkl"), "rb") as f:
#     mapping = pickle.load(f)
#     doc_ids = mapping["doc_ids"]
#     documents = mapping["documents"]
#     doc_titles = mapping["doc_titles"]
#     doc_texts = mapping["doc_texts"]
# print(f"Loaded index with {index.ntotal:,} vectors")